### ISSUE TITLE
Compatibility issue with flake8 version <=6.x.x

### ISSUE THREAD

**Issue by jerinpetergeorge** [asottile/flake8-typing-imports#126]
Hi, 

I'm getting an error while running the `flake8` command. I think `flake8-typing-imports` is causing the error.

### Versions
* `flake8==6.0.0`
* `flake8-typing-imports==1.10.0`
* `Python 3.8.10`

### Error Traceback
```
Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/flake8/main/cli.py", line 23, in main
    app.run(argv)
  File "/usr/local/lib/python3.8/dist-packages/flake8/main/application.py", line 198, in run
    self._run(argv)
  File "/usr/local/lib/python3.8/dist-packages/flake8/main/application.py", line 186, in _run
    self.initialize(argv)
  File "/usr/local/lib/python3.8/dist-packages/flake8/main/application.py", line 165, in initialize
    self.plugins, self.options = parse_args(argv)
  File "/usr/local/lib/python3.8/dist-packages/flake8/options/parse_args.py", line 51, in parse_args
    option_manager.register_plugins(plugins)
  File "/usr/local/lib/python3.8/dist-packages/flake8/options/manager.py", line 259, in register_plugins
    add_options(self)
  File "/usr/local/lib/python3.8/dist-packages/flake8_typing_imports.py", line 901, in add_options
    option_manager.add_option(
  File "/usr/local/lib/python3.8/dist-packages/flake8/options/manager.py", line 281, in add_option
    self._current_group.add_argument(*option_args, **option_kwargs)
  File "/usr/lib/python3.8/argparse.py", line 1385, in add_argument
    raise ValueError('%r is not callable' % (type_func,))
ValueError: 'str' is not callable

```

**Workaround**: Pin the version of `flake8` to `5.x.x`

**Comment by asottile** [comment]
https://youtu.be/cGYVGVsXNFM
